#!/bin/busybox sh
set -eu

command="${1:-serve}"
if [ "$#" -gt 0 ]; then
  shift
fi

case "$command" in
  prepare)
    [ "$(/bin/busybox id -u)" = 0 ] || {
      printf '%s\n' 'tinrelayd prepare must run as root' >&2
      exit 1
    }
    /bin/busybox mkdir -p /var/lib/tinrelay
    /bin/busybox chown 10001:10001 /var/lib/tinrelay
    /bin/busybox chmod 0700 /var/lib/tinrelay
    ;;
  serve)
    [ "$(/bin/busybox id -u)" != 0 ] || {
      printf '%s\n' 'tinrelayd serve refuses to run as root' >&2
      exit 1
    }
    : "${TINRELAY_SOURCE_REPOSITORY:?TINRELAY_SOURCE_REPOSITORY is required}"
    set -- \
      /usr/local/bin/tinrelayd serve \
      --database /var/lib/tinrelay/tinrelay.db \
      --bind 0.0.0.0 \
      --port 8787 \
      --source-repository "$TINRELAY_SOURCE_REPOSITORY" \
      --bootstrap-template /opt/tinrelay/templates/common-bootstrap.md \
      "$@"
    if [ -s /run/secrets/bootstrap_token ]; then
      exec "$@" --bootstrap-token-file - < /run/secrets/bootstrap_token
    fi
    exec "$@"
    ;;
  *)
    exec /usr/local/bin/tinrelayd "$command" "$@"
    ;;
esac
